-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS tagged_file CASCADE;
DROP TABLE IF EXISTS tag CASCADE;
DROP TABLE IF EXISTS file_metadata CASCADE;
DROP TABLE IF EXISTS message CASCADE;
DROP TABLE IF EXISTS registered_user CASCADE;